spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver  #???????
    username: root #mysql?????
    password: dy20020618 #mysql????
    url: jdbc:mysql://localhost:3306/sports?characterEncoding=utf8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource #?????

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #????
  type-aliases-package: com.example.entity #???????????????????
  mapper-locations: classpath:*/*Mapper.xml #?? mapper??


server:
  port: 8080

