spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
<<<<<<< HEAD
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Heyvan1009
    url: jdbc:mysql://localhost:3306/demo
=======

    driver-class-name: com.mysql.cj.jdbc.Driver  #???????
    username: root #mysql?????
    password: dy20020618 #mysql????
    url: jdbc:mysql://localhost:3306/sports?characterEncoding=utf8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource #?????
  flyway:
    encoding: utf-8
>>>>>>> 0c4f1a5 (修改了数据库和后端代码)

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
